# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c862789b8a79a42bab4d562da06a1a055819a9e7f4882668cba6182fc140f76baffeaa28ac797633397f6aa5046b057294b696452fe3e7d426fee7cf1acb4e1

test:
  secret_key_base: 101ae82da959d775d91783836b930a7cb2b74d638701e3892c0a250d6d551626223df74304f6c0eb75ebf2d7ad12e8f322ab1abeab67d0c33505c84bf63660ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
